### ISSUE TITLE
Does not work in the background.

### ISSUE THREAD

**Issue by dlenkes** [williamruckman/WIFIBadger#1]
Hello,

I have a Galaxy S10+ , with android 9.

It runs, I disabled battery optimization, the notification is constantly displayed, so I know that the app is running.

I go to the other end of the house where the signal is weak, but the signal from the other router (same ssid) is strong, and wait: nothing happens.
As soon as I click on the notification, which brings the app to the foreground, I see the wifi disconnecting and reconnecting.

Do you know what can be the issue when it is in the background?

Thanks,
Daniel

**Comment by williamruckman** [comment]
This application uses google APIs to interact with the Android device. 

Since API level 24 (Nougat) Android 7.0, Google began removing API calls that this application relies on as they deemed them to be a security risk or a optimization issue and removed the backward compatibility as well.

So, unfortunately, some background tasks will never work at your android level unless you wish to code a root version of this application. Which is why I am offering up the source code.

You are welcome to have at it! But I am done continually chasing google's tail. I am a programmer of one and it took me 6 months to write this as it is, for free. I don't have the time to re-write my code every time google changes their APIs on a whim.

Here is a list of things that google has done to make useful application such as this no longer work:

**Android 7.0:**
Doze on the Go... "with screen off and on battery for a period of time, Doze applies the full CPU and network restrictions on PowerManager.WakeLock, AlarmManager alarms, and GPS/Wi-Fi scans"

Project Svelte: Background Optimizations "In Android 7.0 we're removing three commonly-used implicit broadcasts"

**Android 8.0:**
Background Service Limitations
Broadcast Limitations

**Comment by dlenkes** [comment]
Sad, but thanks for the reply!
